apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-db-cluster-kurtarildi
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.14
  
  bootstrap:
    recovery:
      source: test-db-cluster # Yedeklerin çekileceği orijinal kümenin adı
      recoveryTarget:
        # Tabloyu silmeden önceki not ettiğiniz o tam saniyeyi buraya yazın
        targetTime: "2026-06-10 12:24:10.909165+00" 

  # Yedeklerin durduğu MinIO bilgilerini veriyoruz
  externalClusters:
    - name: test-db-cluster
      barmanObjectStore:
        destinationPath: s3://postgres-backups/
        endpointURL: http://minio-service.default.svc.cluster.local:9000
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio-creds
            key: ACCESS_SECRET_KEY
  storage:
    size: 5Gi
